name: Docs

on:
  push:
    branches:
      - main

jobs:
  deploy_docs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy docs
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      - name: Install build tools
        run: |
          python -m pip install -U pip==20.2.4
          python -m pip install -U setuptools==47.3.1
          python -m pip install -U poetry==1.1.4
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory only)
        run: python -m poetry install --extras "baseline examples-tensorflow examples-pytorch http-logger ops"
      - name: Build and deploy docs
        env:
          AWS_DEFAULT_REGION: ${{ secrets. AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
        run: ./dev/deploy-docs.sh
