name: Build Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_core:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: [3.6.11, 3.7.9, 3.8.3]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install build tools
        run: |
          python -m pip install -U pip==20.2.4
          python -m pip install -U setuptools==49.3.1
          python -m pip install -U poetry==1.1.4
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory only)
        run: python -m poetry install
      - name: Check if protos need recompilation
        run: ./dev/check-protos.sh
      - name: Lint + Test (isort/black/docformatter/mypy/pylint/flake8/pytest)
        run: ./dev/test.sh

  test_baseline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      - name: Install build tools
        run: |
          python -m pip install -U pip==20.2.4
          python -m pip install -U setuptools==49.3.1
          python -m pip install -U poetry==1.0.10
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory + optional)
        run: |
          python -m poetry install --extras "baseline"
          python -m pip install -U tensorflow-cpu==2.3.1
      - name: Cache Datasets
        uses: actions/cache@v2
        with:
          path: '~/.keras'
          key: keras-datasets
      - name: Download Datasets
        run: |
          python -c "import tensorflow as tf; tf.keras.datasets.cifar10.load_data()"
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./dev/test-baseline.sh

  test_example_pytorch:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      - name: Install build tools
        run: |
          python -m pip install -U pip==20.2.4
          python -m pip install -U setuptools==49.3.1
          python -m pip install -U poetry==1.1.4
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory + optional)
        run: |
          python -m poetry install --extras "examples-pytorch"
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./dev/test-example-pytorch.sh

  test_example_tensorflow:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      - name: Install build tools
        run: |
          python -m pip install -U pip==20.2.4
          python -m pip install -U setuptools==49.3.1
          python -m pip install -U poetry==1.1.4
          poetry config virtualenvs.create false
      - name: Install dependencies (mandatory + optional)
        run: |
          python -m poetry install --extras "examples-tensorflow"
          python -m pip install -U tensorflow-cpu==2.3.1
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./dev/test-example-tensorflow.sh
